### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by tolmasky** [scripted-editor/scripted#302]
npm ERR! fetch failed https://github.com/cujojs/when/archive/noisy-deferred-then.tar.gz
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/fetch.js:58:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:129:20)
npm ERR!     at evalmachine.<anonymous>:1604:14
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:97:15)
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

**Comment by chipmccormick** [comment]
and another

**Comment by danShumway** [comment]
Same with me:
https://github.com/cujojs/when/archive/noisy-deferred-then.tar.gz doesn't exist, although when is a valid github repo.
