### ISSUE TITLE
npm install after repo clone fails 

### ISSUE THREAD

**Issue by jasonpolites** [scripted-editor/scripted#305]
I tried the simple `npm install -g scripted`, that failed with the same error reported [here](https://github.com/scripted-editor/scripted/issues/302), so I tried cloning the repo but that fails too:

```
npm install

> rbytes@0.0.2 install /[redacted]/projects/scripted/node_modules/rbytes
> node-waf configure build

sh: node-waf: command not found
npm WARN install:rbytes@0.0.2 rbytes@0.0.2 install: `node-waf configure build`
npm WARN install:rbytes@0.0.2 spawn ENOENT

> scripted@0.5.0 postinstall /[redacted]/projects/scripted
> cd client && bower install

bower cloning https://github.com/requirejs/i18n.git
bower cloning https://github.com/cujojs/when.git
bower cloning https://github.com/Constellation/doctrine.git
bower cloning https://github.com/aseemk/json5.git
child_process.js:309
    throw new TypeError('options argument must be an object');
    ^

TypeError: options argument must be an object
    at normalizeSpawnArguments (child_process.js:309:11)
    at exports.spawn (child_process.js:333:38)
    at module.exports (/Users/Jason/projects/scripted/node_modules/bower/lib/util/spawn.js:17:12)
    at module.exports (/Users/Jason/projects/scripted/node_modules/bower/lib/util/git-cmd.js:19:12)
    at null.<anonymous> (/Users/Jason/projects/scripted/node_modules/bower/lib/core/package.js:611:18)
    at /Users/Jason/projects/scripted/node_modules/mkdirp/index.js:20:20
    at FSReqWrap.oncomplete (fs.js:82:15)

```

**Comment by jasonpolites** [comment]
`npm install -g https://github.com/scripted-editor/scripted/tarball/master` fails with same error.

This is on Mac OSX 10.11.5

**Comment by vaalgit** [comment]
same too.
